<!DOCTYPE html>
<html>

<body>

<?php 
/*
// Check if image file is a actual image or fake image
if(isset($_POST["fileToUpload"])) {
	$check = getimagesize($_FILES["fileToUpload"]["tmp_name"]);
	if($check !== false) {
		echo "File is an image - " . $check["mime"] . ".";
		$uploadOk = 1;
	} else {
		echo "File is not an image.";
		$uploadOk = 0;
	}
}
*/
?>
<!-- 
<form action="/device/updatePhotos" method="post" enctype="multipart/form-data">
    Select image to upload:<br>
    <input type="file" name="photos[0]" id="photos"><br>
    <input type="file" name="photos[1]" id="photos"><br>
    <input type="file" name="photos[2]" id="photos"><br>
    <input type="file" name="photos[3]" id="photos"><br>
    <input type="file" name="photos[4]" id="photos"><br>
    <input type="file" name="photos[5]" id="photos"><br>
    <input type="file" name="photos[6]" id="photos"><br>
    <input type="file" name="photos[7]" id="photos"><br>
    <input type="file" name="photos[8]" id="photos"><br>
    <input type="file" name="photos[9]" id="photos"><br>
    <input type="file" multiple="" name="photos[]" id="photos"><br>
    <input type="submit" value="Upload Image" name="gos">
</form>
 -->

<form action="/device/update" method="post" enctype="multipart/form-data">
    Select image to upload:<br>
	<input type="file" name="photos" id="photos"><br>
	<input type="submit" value="Upload Image" name="gos">
</form>

</body>
</html>

